import Head from 'next/head'
import m from "../public/m.png"
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div style={{display : 'flex',justifyContent : "center",alignContent : "center"}}>
            <h1>My Personal Site is under renovation</h1>

      <p>Naga Sai</p>
     </div>
     
     <div style={{display : 'flex',justifyContent : "center"}}>
     <Image  src={m} width="600" height={'400'} alt=''></Image>
     </div>
   
    </>
  )
}
